import operator
from typing import Annotated, TypedDict

from langgraph.graph.message import add_messages


class AgentState(TypedDict):
    messages: Annotated[list, add_messages]
    plan: list[str]  # The list of steps generated by the Planner
    completed_steps: Annotated[
        list[str], operator.add
    ]  # Tracks what the Worker has finishe
    final_draft: str  # The document the Critic will review
